# Generated by Django 4.1 on 2022-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comprador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=200)),
                ("dni", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion_emisora", models.CharField(max_length=200)),
                ("direccion_receptora", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("metodo_envio", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=200)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=200)),
                ("dni", models.IntegerField()),
            ],
        ),
    ]
