# Generated by Django 4.1 on 2022-09-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppEcommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envio",
            name="descripcion",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.IntegerField(),
        ),
    ]
